# Generated by Django 5.2.4 on 2025-11-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
